name: Release

permissions: {}

on:
  push:
    tags: ['v2.[0-9]+.[0-9]+']

jobs:
  release:
    permissions:
      actions: read
      attestations: write
      artifact-metadata: write
      contents: write
      discussions: write
      id-token: write
    uses: panva/.github/.github/workflows/npm-release.yml@3faba8af3880247be43547787aedd52780c9f946
    with:
      cleanup_paths: '["build"]'
