name: Test

permissions: {}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '11 11 * * 1'
  workflow_dispatch:

jobs:
  node-versions:
    uses: panva/.github/.github/workflows/node-versions.yml@3faba8af3880247be43547787aedd52780c9f946
    with:
      min: 20

  test:
    needs:
      - node-versions
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        node-version: ${{ fromJSON(needs.node-versions.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm clean-install
      - run: npm test
